name: "【Docker】Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-htmlbeautifier:
    name: Run htmlbeautifier
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Docker Compose をインストールするステップを追加
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Docker Compose を使った HTML Beautifier の実行
    - name: Run htmlbeautifier on docker-compose
      run: |
        docker-compose build
        docker-compose run --rm web bin/setup
        docker-compose run --rm web bin/htmlbeautifier
        git diff --exit-code